#!/bin/sh

# Public domain notice for all NCBI EDirect scripts is located at:
# https://www.ncbi.nlm.nih.gov/books/NBK179288/#chapter6.Public_Domain_Notice

if [ "$#" -eq 0 ]
then
  echo "Must supply path for indexed files"
  exit 1
fi

target="$1"
shift

target=${target%/}

if [ "$#" -eq 0 ]
then
  echo "Must supply path for data files"
  exit 1
fi

data="$1"
shift

data=${data%/}

find "$target" -name "*.e2x" -delete
find "$target" -name "*.e2x.gz" -delete

if [ -f "pubmed001.xml.gz" ]
then
  for fl in *.xml.gz
  do
    base=${fl%.xml.gz}
    echo "$base.e2x"
    if [ -s "$data/meshtree.txt" ]
    then
      gunzip -c "$fl" |
      xtract -transform "$data/meshtree.txt" -e2index |
      gzip -1 > "$target/$base.e2x.gz"
    else
      gunzip -c "$fl" |
      xtract -e2index |
      gzip -1 > "$target/$base.e2x.gz"
    fi
    sleep 1
  done
elif [ -f "pubmed001.xml" ]
then
  for fl in *.xml
  do
    base=${fl%.xml}
    echo "$base.e2x"
    if [ -s "$data/meshtree.txt" ]
    then
      cat "$fl" |
      xtract -transform "$data/meshtree.txt" -e2index |
      gzip -1 > "$target/$base.e2x.gz"
    else
      cat "$fl" |
      xtract -e2index |
      gzip -1 > "$target/$base.e2x.gz"
    fi
    sleep 1
  done
fi
